%mex CC=g++ CXX=g++ LD=g++ -g -v -O0 -Wall -c -fmessage-length=0...
%-I"/home/falter/falter_eclipse_new/org.fortiss.falter.extern" ...
%org.fortiss.falter.euler.c

mex CC=gcc CXX=gcc LD=gcc -v -g LDFLAGS="\$LDFLAGS -Wall" -DSIMULATION -DCONTROL_SFUNCTION -lprotobuf ...
-I"control" ...
-I"simulation" ...
control/control.cpp ...
control/exchange.pb.cpp ...
simulation/falter_control_sfunction.c

%mex CC=gcc LD=gcc -g -v LDFLAGS="\$LDFLAGS -Wall" -DSIMULATION -DSHAREDMEMORY_SFUNCTION ...
%-I"org.fortiss.falter.simulation" ...
%-I"org.fortiss.falter.datacom" ...
%org.fortiss.falter.simulation/falter_sharedMemory_sfunction.c

% mex CC=gcc LD=gcc -g -v LDFLAGS="\$LDFLAGS -Wall" -DSIMULATION -DPMD_SFUNCTION ...
% -I"simulation" ...
% -I"datacom" ...
% -I"falter.pmd" ...
% simulation/falter_pmd_sfunction.c ...
% simulation/pmd.c
% datacom/pmd_data.c ...
% pmd/pmd.c

% mex CC=gcc LD=gcc -g -v LDFLAGS="\$LDFLAGS -Wall" -DSIMULATION -DPMD_SFUNCTION ...
% -I"org.fortiss.falter.simulation" ...
% -I"org.fortiss.falter.datacom" ...
% -I"org.fortiss.falter.pmd" ...
% org.fortiss.falter.simulation/falter_pmd_sfunction.c ...
% org.fortiss.falter.datacom/pmd_data.c ...
% org.fortiss.falter.pmd/pmd.c
% 
% mex CC=g++ CXX=g++ LD=g++ -g -v LDFLAGS="\$LDFLAGS -Wall" -DSIMULATION -DFLIGHTMANAGEMENT_SFUNCTION ...
% -I"org.fortiss.falter.simulation" ...
% -I"org.fortiss.falter.execution" ...
% -I"org.fortiss.falter.datacom" ...
% -I"org.fortiss.falter.pathfinding" ...
% -I"org.fortiss.falter.environment" ...
% -I"org.fortiss.falter.perception" ...
% -I"org.fortiss.falter.util" ...
% org.fortiss.falter.simulation/falter_flightmanagement_sfunction.cpp ...
% org.fortiss.falter.execution/flight_management.cpp ...
% org.fortiss.falter.datacom/ctrl_ref.c ...
% org.fortiss.falter.util/stack.c ...
% org.fortiss.falter.util/uav_time.c ...
% org.fortiss.falter.datacom/obstacle_notification.c ...
% org.fortiss.falter.datacom/uav_environment.c ...
% org.fortiss.falter.datacom/position_motion.c ...
%org.fortiss.falter.environment/base_environment.c ...
%org.fortiss.falter.pathfinding/compute_path.cpp ...
%org.fortiss.falter.pathfinding/a_star.cpp ...
%org.fortiss.falter.pathfinding/node.cpp ...
%org.fortiss.falter.pathfinding/star_environment.cpp ...
%org.fortiss.falter.pathfinding/star_base.cpp ...
%org.fortiss.falter.pathfinding/a_node_comparator.cpp ...
%org.fortiss.falter.pathfinding/my_list.cpp ...
%org.fortiss.falter.pathfinding/comparator.cpp ...
%org.fortiss.falter.pathfinding/lpa_star.cpp ...
%org.fortiss.falter.util/logging.c ...
%org.fortiss.falter.pathfinding/lpa_node_comparator.cpp

% Build perception code
% mex CC=gcc LD=gcc -g -v LDFLAGS="\$LDFLAGS -Wall" -DSIMULATION ...
% -I"org.fortiss.falter.simulation" ...
% -I"org.fortiss.falter.perception" ...
% -I"org.fortiss.falter.datacom" ...
% -I"org.fortiss.falter.util" ...
% -I"org.fortiss.falter.geometry" ...
% -I"roboio"...
% -L"org.fortiss.falter.geometry/Debug"...
% -l"geometry"...
% org.fortiss.falter.simulation/falter_perception_sfunction.c ...
% org.fortiss.falter.perception/perception.c ...
% org.fortiss.falter.util/i2cFalter.c ...
% org.fortiss.falter.util/srf08.c ...
% org.fortiss.falter.perception/laser.c ...
% org.fortiss.falter.datacom/obstacle_notification.c ...
% org.fortiss.falter.datacom/uav_environment.c ...
% org.fortiss.falter.util/uav_time.c ...
% org.fortiss.falter.util/filter.c ...
% org.fortiss.falter.util/logging.c ...
% org.fortiss.falter.util/ad.c ...
% org.fortiss.falter.datacom/position_motion.c...
% org.fortiss.falter.datacom/error_notification.c


mex simulation/Library/checkForZeroWall.c
mex simulation/Library/minSensorResults.c
mex simulation/Library/minSensorResults_old.c